import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Header } from '@/components/Header'
import { Card } from '@/components/Card'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full max-w-6xl mx-auto">
        <section className='w-full flex'>

          <div className='w-full lg:w-1/2 p-5'>
            <h1 className="text-3xl font-bold">Track your goals with Kodaps OKR</h1>
            <h2>Become more productive while having fun</h2><br/>
            <a className="bg-slate-100 p-2 text-slate-600">Get Started</a>
          </div>
          <div className='flex w-full lg:w-1/2 p-5'>
              <Image className="w-full" width="640" height="480" alt="journey in to code" src="/lines_of_code.png"/>
          </div>

        </section>

        <section className='text-center p-5'>
          <h3 className='text-xl font-semibold'>These advantages await !</h3>
          <div className='w-full flex justify-around pt-5'>
            <Card>Card 1</Card>
            <Card>Card 2</Card>
          </div>
          
        </section>
      </main>
    </>
  )
}
